# Generated by Django 5.2.3 on 2025-07-30 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('edicion', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=7)),
                ('isbn', models.CharField(max_length=50)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portada/')),
                ('valor_saberes', models.BigIntegerField()),
                ('resenia', models.TextField(blank=True, null=True)),
                ('genero', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('saber', models.IntegerField(default=0)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='catalogo.libro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
